import type { Env } from "../env";
import { applyCatalogSeed, type CatalogSeed } from "./catalog-seed";

const item = (slug: string) => `https://www.valheim.tools/items/${slug}`;
const building = (slug: string) => `https://www.valheim.tools/building/${slug}`;

const mistlandsSeed: CatalogSeed = {
  marker: "catalog_mistlands_acquisition_v1",
  biome: "mistlands",
  stations: [
    { slug: "black-forge", en: "Black Forge", ru: "Чёрная кузница" },
    { slug: "galdr-table", en: "Galdr Table", ru: "Стол гальдра" },
    { slug: "eitr-refinery", en: "Eitr Refinery", ru: "Эйтровый очиститель" },
    { slug: "artisan-table", en: "Artisan Table", ru: "Стол ремесленника" }
  ],
  items: [
    { slug:"torn-spirit", type:"resource", category:"material", en:"Torn Spirit", ru:"Разорванный дух", descriptionEn:"A fragment of Yagluth's spirit used to attract wisps.", descriptionRu:"Фрагмент духа Яглута, используемый для привлечения огоньков.", imageFile:"Torn_spirit.png", source:item("torn-spirit"), biome:"plains" },
    { slug:"wisp", type:"resource", category:"material", en:"Wisp", ru:"Огонёк", descriptionEn:"A tiny spirit gathered from a Wisp Fountain at night.", descriptionRu:"Маленький дух, собираемый ночью у фонтана огоньков.", imageFile:"Wisp.png", source:item("wisp") },
    { slug:"yggdrasil-wood", type:"resource", category:"material", en:"Yggdrasil Wood", ru:"Древесина Иггдрасиля", descriptionEn:"Tough wood chopped from Yggdrasil shoots in the Mistlands.", descriptionRu:"Прочная древесина из побегов Иггдрасиля в Туманных землях.", imageFile:"Yggdrasil_wood.png", source:item("yggdrasil-wood") },
    { slug:"black-marble", type:"resource", category:"material", en:"Black Marble", ru:"Чёрный мрамор", descriptionEn:"Dense stone carved from giant remains and Dvergr structures.", descriptionRu:"Плотный камень из останков гигантов и построек двергов.", imageFile:"Black_marble.png", source:item("black-marble") },
    { slug:"black-core", type:"resource", category:"material", en:"Black Core", ru:"Чёрное ядро", descriptionEn:"A rare core found mainly inside Infested Mines.", descriptionRu:"Редкое ядро, встречающееся главным образом в Заражённых шахтах.", imageFile:"Black_core.png", source:item("black-core") },
    { slug:"soft-tissue", type:"resource", category:"material", en:"Soft Tissue", ru:"Мягкая ткань", descriptionEn:"Arcane tissue harvested from petrified remains and Dvergr loot.", descriptionRu:"Магическая ткань из окаменевших останков и добычи двергов.", imageFile:"Soft_tissue.png", source:item("soft-tissue") },
    { slug:"sap", type:"resource", category:"material", en:"Sap", ru:"Сок", descriptionEn:"Magical sap extracted from Yggdrasil roots.", descriptionRu:"Магический сок, добываемый из корней Иггдрасиля.", imageFile:"Sap.png", source:item("sap") },
    { slug:"refined-eitr", type:"resource", category:"material", en:"Refined Eitr", ru:"Очищенный эйтр", descriptionEn:"Volatile magical matter refined from sap and soft tissue.", descriptionRu:"Нестабильная магическая материя из сока и мягкой ткани.", imageFile:"Refined_eitr.png", source:item("refined-eitr") },
    { slug:"carapace", type:"resource", category:"material", en:"Carapace", ru:"Панцирь", descriptionEn:"Hard shell plates dropped by Seekers.", descriptionRu:"Твёрдые панцирные пластины, выпадающие из Искателей.", imageFile:"Carapace.png", source:item("carapace") },
    { slug:"mandible", type:"resource", category:"material", en:"Mandible", ru:"Жвала", descriptionEn:"A massive jaw part dropped by Seeker Soldiers.", descriptionRu:"Массивная часть челюсти Искателя-солдата.", imageFile:"Mandible.png", source:item("mandible") },
    { slug:"scale-hide", type:"resource", category:"material", en:"Scale Hide", ru:"Чешуйчатая шкура", descriptionEn:"Tough hide harvested from Hares.", descriptionRu:"Прочная чешуйчатая шкура, добываемая с зайцев.", imageFile:"Scale_hide.png", source:item("scale-hide") },
    { slug:"blood-clot", type:"resource", category:"material", en:"Blood Clot", ru:"Сгусток крови", descriptionEn:"A blood-magic material dropped by Ticks.", descriptionRu:"Материал кровавой магии, выпадающий из клещей.", imageFile:"Blood_clot.png", source:item("blood-clot") },
    { slug:"bilebag", type:"resource", category:"material", en:"Bilebag", ru:"Желчный мешок", descriptionEn:"A volatile organ dropped by Gjalls.", descriptionRu:"Нестабильный орган, выпадающий из гьяллов.", imageFile:"Bilebag.png", source:item("bilebag") },
    { slug:"royal-jelly", type:"resource", category:"material", en:"Royal Jelly", ru:"Королевское желе", descriptionEn:"Rich jelly gathered from Infested Mines.", descriptionRu:"Питательное желе из Заражённых шахт.", imageFile:"Royal_jelly.png", source:item("royal-jelly") },
    { slug:"seeker-meat", type:"resource", category:"material", en:"Seeker Meat", ru:"Мясо Искателя", descriptionEn:"Raw meat from Seekers.", descriptionRu:"Сырое мясо Искателей.", imageFile:"Seeker_meat.png", source:item("seeker-meat") },
    { slug:"hare-meat", type:"resource", category:"material", en:"Hare Meat", ru:"Мясо зайца", descriptionEn:"Raw meat from Mistlands Hares.", descriptionRu:"Сырое мясо зайцев Туманных земель.", imageFile:"Hare_meat.png", source:item("hare-meat") },
    { slug:"chicken-meat", type:"resource", category:"material", en:"Chicken Meat", ru:"Куриное мясо", descriptionEn:"Raw meat from chickens.", descriptionRu:"Сырое куриное мясо.", imageFile:"Chicken_meat.png", source:item("chicken-meat") },
    { slug:"egg", type:"resource", category:"material", en:"Egg", ru:"Яйцо", descriptionEn:"An egg that can be cooked or hatched.", descriptionRu:"Яйцо, которое можно приготовить или вывести цыплёнка.", imageFile:"Egg.png", source:item("egg") },
    { slug:"magecap", type:"resource", category:"material", en:"Magecap", ru:"Магический гриб", descriptionEn:"A cultivated Mistlands mushroom rich in eitr.", descriptionRu:"Выращиваемый гриб Туманных земель, богатый эйтром.", imageFile:"Magecap.png", source:item("magecap") },
    { slug:"jotun-puffs", type:"resource", category:"material", en:"Jotun Puffs", ru:"Йотунские пуховики", descriptionEn:"A cultivated Mistlands mushroom used in advanced food.", descriptionRu:"Выращиваемый гриб Туманных земель для продвинутой еды.", imageFile:"Jotun_puffs.png", source:item("jotun-puffs") },
    { slug:"dvergr-extractor", type:"resource", category:"material", en:"Dvergr Extractor", ru:"Двергский экстрактор", descriptionEn:"A component recovered from protected Dvergr crates.", descriptionRu:"Компонент из защищённых ящиков двергов.", imageFile:"Dvergr_extractor.png", source:item("dvergr-extractor") },
    { slug:"mechanical-spring", type:"resource", category:"material", en:"Mechanical Spring", ru:"Механическая пружина", descriptionEn:"An artisan component used in advanced machinery.", descriptionRu:"Ремесленный компонент для продвинутых механизмов.", imageFile:"Mechanical_spring.png", source:item("mechanical-spring") },
    { slug:"sealbreaker-fragment", type:"resource", category:"material", en:"Sealbreaker Fragment", ru:"Фрагмент разрушителя печатей", descriptionEn:"One of nine fragments needed to craft the Queen's key.", descriptionRu:"Один из девяти фрагментов ключа к Королеве.", imageFile:"Sealbreaker_fragment.png", source:item("sealbreaker-fragment") },
    { slug:"hook", type:"resource", category:"material", en:"Hook", ru:"Крюк", descriptionEn:"A heavy hook found in ruined Dvergr guard towers.", descriptionRu:"Тяжёлый крюк из разрушенных сторожевых башен двергов.", imageFile:"Hook.png", source:item("hook") },
    { slug:"gjall-trophy", type:"resource", category:"trophy", en:"Gjall Trophy", ru:"Трофей: гьялл", descriptionEn:"A rare trophy from Gjalls.", descriptionRu:"Редкий трофей с гьяллов.", imageFile:"Gjall_trophy.png", source:item("gjall-trophy") },
    { slug:"seeker-trophy", type:"resource", category:"trophy", en:"Seeker Trophy", ru:"Трофей: Искатель", descriptionEn:"A trophy from Seekers.", descriptionRu:"Трофей с Искателей.", imageFile:"Seeker_trophy.png", source:item("seeker-trophy") },
    { slug:"black-marble-battle-idol", type:"resource", category:"material", en:"Black Marble Battle Idol", ru:"Боевой идол чёрного мрамора", descriptionEn:"Mistlands-tier weapon refinement idol.", descriptionRu:"Идол Туманных земель для усиления оружия.", imageFile:"Black_Marble_Battle_Idol.png", source:item("black-marble-battle-idol") },
    { slug:"black-marble-protection-idol", type:"resource", category:"material", en:"Black Marble Protection Idol", ru:"Защитный идол чёрного мрамора", descriptionEn:"Mistlands-tier armour refinement idol.", descriptionRu:"Идол Туманных земель для усиления брони.", imageFile:"Black_Marble_Protection_Idol.png", source:item("black-marble-protection-idol") },

    { slug:"mistwalker", type:"item", category:"weapon", en:"Mistwalker", ru:"Туманный странник", descriptionEn:"A silver-and-eitr sword that clears mist and deals frost damage.", descriptionRu:"Меч из серебра и эйтра, рассеивающий туман и наносящий морозный урон.", imageFile:"Mistwalker.png", source:item("mistwalker") },
    { slug:"jotun-bane", type:"item", category:"weapon", en:"Jotun Bane", ru:"Погибель йотунов", descriptionEn:"A poisonous axe forged from Mistlands materials.", descriptionRu:"Ядовитый топор из материалов Туманных земель.", imageFile:"Jotun_bane.png", source:item("jotun-bane") },
    { slug:"demolisher", type:"item", category:"weapon", en:"Demolisher", ru:"Разрушитель", descriptionEn:"A colossal sledgehammer with enormous area damage.", descriptionRu:"Огромная кувалда с мощным уроном по площади.", imageFile:"Demolisher.png", source:item("demolisher") },
    { slug:"skull-splittur", type:"item", category:"weapon", en:"Skull Splittur", ru:"Раскалыватель черепов", descriptionEn:"A heavy two-handed axe introduced with Valheim 1.0.", descriptionRu:"Тяжёлый двуручный топор, добавленный в Valheim 1.0.", imageFile:"Skull_Splittur.png", source:item("skull-splittur") },
    { slug:"krom", type:"item", category:"weapon", en:"Krom", ru:"Кром", descriptionEn:"A massive two-handed iron-and-bronze sword.", descriptionRu:"Массивный двуручный меч из железа и бронзы.", imageFile:"Krom.png", source:item("krom") },
    { slug:"himminafl", type:"item", category:"weapon", en:"Himminafl", ru:"Химминафл", descriptionEn:"An atgeir charged with lightning.", descriptionRu:"Атгейр, заряженный молнией.", imageFile:"Himminafl.png", source:item("himminafl") },
    { slug:"carapace-spear", type:"item", category:"weapon", en:"Carapace Spear", ru:"Панцирное копьё", descriptionEn:"A deadly spear of carapace and mandible.", descriptionRu:"Смертоносное копьё из панциря и жвал.", imageFile:"Carapace_spear.png", source:item("carapace-spear") },
    { slug:"spinesnap", type:"item", category:"weapon", en:"Spinesnap", ru:"Позвоночный лук", descriptionEn:"A brutal bow of bone and refined eitr.", descriptionRu:"Мощный лук из костей и очищенного эйтра.", imageFile:"Spinesnap.png", source:item("spinesnap") },
    { slug:"arbalest", type:"item", category:"weapon", en:"Arbalest", ru:"Арбалет", descriptionEn:"The first player-crafted crossbow.", descriptionRu:"Первый доступный игроку арбалет.", imageFile:"Arbalest.png", source:item("arbalest") },
    { slug:"skoll-and-hati", type:"item", category:"weapon", en:"Skoll and Hati", ru:"Сколль и Хати", descriptionEn:"A pair of fast black-metal knives.", descriptionRu:"Пара быстрых ножей из чёрного металла.", imageFile:"Skoll_and_Hati.png", source:item("skoll-and-hati") },
    { slug:"carapace-shield", type:"item", category:"weapon", en:"Carapace Shield", ru:"Панцирный щит", descriptionEn:"A heavy shield of carapace, scale hide and eitr.", descriptionRu:"Тяжёлый щит из панциря, чешуйчатой шкуры и эйтра.", imageFile:"Carapace_shield.png", source:item("carapace-shield") },
    { slug:"carapace-buckler", type:"item", category:"weapon", en:"Carapace Buckler", ru:"Панцирный баклер", descriptionEn:"A light Mistlands buckler built for parrying.", descriptionRu:"Лёгкий баклер Туманных земель для парирования.", imageFile:"Carapace_buckler.png", source:item("carapace-buckler") },
    { slug:"black-metal-pickaxe", type:"item", category:"tool", en:"Black Metal Pickaxe", ru:"Кирка из чёрного металла", descriptionEn:"A durable pickaxe for late-game mining.", descriptionRu:"Прочная кирка для поздней добычи.", imageFile:"Black_metal_pickaxe.png", source:item("black-metal-pickaxe") },
    { slug:"grappling-hook", type:"item", category:"tool", en:"Grappling Hook", ru:"Крюк-кошка", descriptionEn:"A 1.0 mobility tool for pulling yourself across terrain.", descriptionRu:"Инструмент мобильности 1.0 для перемещения по сложному рельефу.", imageFile:"Grappling_hook.png", source:item("grappling-hook") },
    { slug:"bile-bomb-x3", type:"item", category:"weapon", en:"Bile Bomb ×3", ru:"Желчная бомба ×3", descriptionEn:"Three thrown bombs that burst into fire and poison.", descriptionRu:"Три метательные бомбы с огнём и ядом.", imageFile:"Bile_bomb.png", source:item("bile-bomb") },

    { slug:"staff-of-embers", type:"item", category:"magic", en:"Staff of Embers", ru:"Посох углей", descriptionEn:"An elemental staff that launches explosive fireballs.", descriptionRu:"Стихийный посох, запускающий взрывные огненные шары.", imageFile:"Staff_of_embers.png", source:item("staff-of-embers") },
    { slug:"staff-of-frost", type:"item", category:"magic", en:"Staff of Frost", ru:"Посох мороза", descriptionEn:"A rapid-fire elemental staff of freezing shards.", descriptionRu:"Стихийный посох, быстро выпускающий ледяные осколки.", imageFile:"Staff_of_frost.png", source:item("staff-of-frost") },
    { slug:"staff-of-protection", type:"item", category:"magic", en:"Staff of Protection", ru:"Посох защиты", descriptionEn:"A blood-magic staff that creates protective barriers.", descriptionRu:"Посох кровавой магии, создающий защитные барьеры.", imageFile:"Staff_of_protection.png", source:item("staff-of-protection") },
    { slug:"dead-raiser", type:"item", category:"magic", en:"Dead Raiser", ru:"Воскреситель мёртвых", descriptionEn:"A blood-magic skull that summons skeletal allies.", descriptionRu:"Череп кровавой магии, призывающий скелетов-союзников.", imageFile:"Dead_raiser.png", source:item("dead-raiser") },

    { slug:"carapace-helmet", type:"item", category:"armor", en:"Carapace Helmet", ru:"Панцирный шлем", descriptionEn:"Heavy Mistlands helmet made from seeker shell.", descriptionRu:"Тяжёлый шлем Туманных земель из панциря Искателей.", imageFile:"Carapace_helmet.png", source:item("carapace-helmet") },
    { slug:"carapace-breastplate", type:"item", category:"armor", en:"Carapace Breastplate", ru:"Панцирный нагрудник", descriptionEn:"Heavy carapace body armour.", descriptionRu:"Тяжёлая панцирная броня корпуса.", imageFile:"Carapace_breastplate.png", source:item("carapace-breastplate") },
    { slug:"carapace-greaves", type:"item", category:"armor", en:"Carapace Greaves", ru:"Панцирные поножи", descriptionEn:"Heavy carapace leg armour.", descriptionRu:"Тяжёлая панцирная защита ног.", imageFile:"Carapace_greaves.png", source:item("carapace-greaves") },
    { slug:"eitr-weave-hood", type:"item", category:"armor", en:"Eitr-weave Hood", ru:"Эйтровый капюшон", descriptionEn:"Mage headwear that improves eitr regeneration.", descriptionRu:"Магический капюшон, улучшающий восстановление эйтра.", imageFile:"Eitr_weave_hood.png", source:item("eitr-weave-hood") },
    { slug:"eitr-weave-robe", type:"item", category:"armor", en:"Eitr-weave Robe", ru:"Эйтровая мантия", descriptionEn:"Mage body armour woven with refined eitr.", descriptionRu:"Магическая броня корпуса, сотканная с очищенным эйтром.", imageFile:"Eitr_weave_robe.png", source:item("eitr-weave-robe") },
    { slug:"eitr-weave-trousers", type:"item", category:"armor", en:"Eitr-weave Trousers", ru:"Эйтровые штаны", descriptionEn:"Mage leg armour woven with refined eitr.", descriptionRu:"Магическая защита ног с очищенным эйтром.", imageFile:"Eitr_weave_trousers.png", source:item("eitr-weave-trousers") },
    { slug:"feather-cape", type:"item", category:"armor", en:"Feather Cape", ru:"Перьевой плащ", descriptionEn:"A magical cape that grants feather fall.", descriptionRu:"Магический плащ, дающий эффект мягкого падения.", imageFile:"Feather_cape.png", source:item("feather-cape") },

    { slug:"pulsating-earrings", type:"item", category:"trinket", en:"Pulsating Earrings", ru:"Пульсирующие серьги", descriptionEn:"A trinket that boosts eitr regeneration.", descriptionRu:"Оберег, ускоряющий восстановление эйтра.", imageFile:"Pulsating_Earrings.png", source:item("pulsating-earrings") },
    { slug:"resounding-shackle", type:"item", category:"trinket", en:"Resounding Shackle", ru:"Звенящие оковы", descriptionEn:"A trinket that restores stamina and boosts slash damage.", descriptionRu:"Оберег, восстанавливающий выносливость и усиливающий рубящий урон.", imageFile:"Resounding_Shackle.png", source:item("resounding-shackle") },

    { slug:"sealbreaker", type:"item", category:"other", en:"Sealbreaker", ru:"Разрушитель печатей", descriptionEn:"The key used to enter the Queen's prison.", descriptionRu:"Ключ для входа в темницу Королевы.", imageFile:"Sealbreaker.png", source:item("sealbreaker") },
    { slug:"wisplight", type:"item", category:"tool", en:"Wisplight", ru:"Светильник огонька", descriptionEn:"A bound wisp that clears nearby Mistlands fog.", descriptionRu:"Связанный огонёк, рассеивающий туман вокруг игрока.", imageFile:"Wisplight.png", source:item("wisplight") },

    { slug:"cooked-seeker-meat", type:"item", category:"food", en:"Cooked Seeker Meat", ru:"Жареное мясо Искателя", descriptionEn:"Cooked seeker meat.", descriptionRu:"Приготовленное мясо Искателя.", imageFile:"Cooked_seeker_meat.png", source:item("cooked-seeker-meat") },
    { slug:"cooked-hare-meat", type:"item", category:"food", en:"Cooked Hare Meat", ru:"Жареное мясо зайца", descriptionEn:"Cooked hare meat.", descriptionRu:"Приготовленное мясо зайца.", imageFile:"Cooked_hare_meat.png", source:item("cooked-hare-meat") },
    { slug:"cooked-chicken-meat", type:"item", category:"food", en:"Cooked Chicken Meat", ru:"Жареное куриное мясо", descriptionEn:"Cooked chicken meat.", descriptionRu:"Приготовленное куриное мясо.", imageFile:"Cooked_chicken_meat.png", source:item("cooked-chicken-meat") },
    { slug:"cooked-egg", type:"item", category:"food", en:"Cooked Egg", ru:"Жареное яйцо", descriptionEn:"A cooked egg.", descriptionRu:"Приготовленное яйцо.", imageFile:"Cooked_egg.png", source:item("cooked-egg") },
    { slug:"seeker-aspic-x2", type:"item", category:"food", en:"Seeker Aspic ×2", ru:"Заливное из Искателя ×2", descriptionEn:"Two eitr-rich portions made from Seeker meat.", descriptionRu:"Две порции еды на эйтр из мяса Искателя.", imageFile:"Seeker_aspic.png", source:item("seeker-aspic") },
    { slug:"yggdrasil-porridge", type:"item", category:"food", en:"Yggdrasil Porridge", ru:"Каша Иггдрасиля", descriptionEn:"An eitr food made from sap, barley and royal jelly.", descriptionRu:"Еда на эйтр из сока, ячменя и королевского желе.", imageFile:"Yggdrasil_porridge.png", source:item("yggdrasil-porridge") },
    { slug:"mushroom-omelette", type:"item", category:"food", en:"Mushroom Omelette", ru:"Грибной омлет", descriptionEn:"A high-stamina Mistlands omelette.", descriptionRu:"Омлет Туманных земель с высоким запасом выносливости.", imageFile:"Mushroom_omelette.png", source:item("mushroom-omelette") },
    { slug:"salad-x3", type:"item", category:"food", en:"Salad ×3", ru:"Салат ×3", descriptionEn:"Three stamina-focused salads.", descriptionRu:"Три порции салата на выносливость.", imageFile:"Salad.png", source:item("salad") },
    { slug:"uncooked-misthare-supreme", type:"item", category:"food", en:"Uncooked Misthare Supreme", ru:"Сырой высший зайчатник", descriptionEn:"A prepared hare dish ready for the oven.", descriptionRu:"Подготовленное блюдо из зайца для печи.", imageFile:"Uncooked_misthare_supreme.png", source:item("uncooked-misthare-supreme") },
    { slug:"misthare-supreme", type:"item", category:"food", en:"Misthare Supreme", ru:"Высший зайчатник", descriptionEn:"A powerful Mistlands health meal.", descriptionRu:"Мощная еда Туманных земель на здоровье.", imageFile:"Misthare_supreme.png", source:item("misthare-supreme") },
    { slug:"uncooked-meat-platter", type:"item", category:"food", en:"Uncooked Meat Platter", ru:"Сырая мясная тарелка", descriptionEn:"A prepared mixed-meat platter ready for the oven.", descriptionRu:"Подготовленная мясная тарелка для печи.", imageFile:"Uncooked_meat_platter.png", source:item("uncooked-meat-platter") },
    { slug:"meat-platter", type:"item", category:"food", en:"Meat Platter", ru:"Мясная тарелка", descriptionEn:"A rich late-game health meal.", descriptionRu:"Сытная поздняя еда на здоровье.", imageFile:"Meat_platter.png", source:item("meat-platter") },
    { slug:"uncooked-honey-glazed-chicken", type:"item", category:"food", en:"Uncooked Honey Glazed Chicken", ru:"Сырая курица в медовой глазури", descriptionEn:"Prepared glazed chicken ready for the oven.", descriptionRu:"Подготовленная курица в медовой глазури для печи.", imageFile:"Uncooked_honey_glazed_chicken.png", source:item("uncooked-honey-glazed-chicken") },
    { slug:"honey-glazed-chicken", type:"item", category:"food", en:"Honey Glazed Chicken", ru:"Курица в медовой глазури", descriptionEn:"A strong Mistlands health meal.", descriptionRu:"Сильная еда Туманных земель на здоровье.", imageFile:"Honey_glazed_chicken.png", source:item("honey-glazed-chicken") },
    { slug:"uncooked-stuffed-mushroom", type:"item", category:"food", en:"Uncooked Stuffed Mushroom", ru:"Сырой фаршированный гриб", descriptionEn:"Prepared magecap ready for the oven.", descriptionRu:"Подготовленный магический гриб для печи.", imageFile:"Uncooked_stuffed_mushroom.png", source:item("uncooked-stuffed-mushroom") },
    { slug:"stuffed-mushroom", type:"item", category:"food", en:"Stuffed Mushroom", ru:"Фаршированный гриб", descriptionEn:"A baked Mistlands eitr food.", descriptionRu:"Запечённая еда Туманных земель на эйтр.", imageFile:"Stuffed_mushroom.png", source:item("stuffed-mushroom") },

    { slug:"mead-base-major-healing", type:"item", category:"consumable", en:"Mead Base: Major Healing", ru:"Основа медовухи: большое лечение", descriptionEn:"A late-game healing mead base.", descriptionRu:"Основа поздней лечебной медовухи.", imageFile:"Mead_base_major_healing.png", source:item("mead-base-major-healing") },
    { slug:"major-healing-mead-x6", type:"item", category:"consumable", en:"Major Healing Mead ×6", ru:"Большая лечебная медовуха ×6", descriptionEn:"Six major healing meads.", descriptionRu:"Шесть больших лечебных медовух.", imageFile:"Major_healing_mead.png", source:item("major-healing-mead") },
    { slug:"mead-base-lingering-stamina", type:"item", category:"consumable", en:"Mead Base: Lingering Stamina", ru:"Основа медовухи: длительная выносливость", descriptionEn:"A base for lingering stamina mead.", descriptionRu:"Основа медовухи длительной выносливости.", imageFile:"Mead_base_lingering_stamina.png", source:item("mead-base-lingering-stamina") },
    { slug:"lingering-stamina-mead-x6", type:"item", category:"consumable", en:"Lingering Stamina Mead ×6", ru:"Медовуха длительной выносливости ×6", descriptionEn:"Six lingering stamina meads.", descriptionRu:"Шесть медовух длительной выносливости.", imageFile:"Lingering_stamina_mead.png", source:item("lingering-stamina-mead") },
    { slug:"mead-base-minor-eitr", type:"item", category:"consumable", en:"Mead Base: Minor Eitr", ru:"Основа медовухи: малый эйтр", descriptionEn:"A base for minor eitr mead.", descriptionRu:"Основа малой медовухи эйтра.", imageFile:"Mead_base_minor_eitr.png", source:item("mead-base-minor-eitr") },
    { slug:"minor-eitr-mead-x6", type:"item", category:"consumable", en:"Minor Eitr Mead ×6", ru:"Малая медовуха эйтра ×6", descriptionEn:"Six minor eitr meads.", descriptionRu:"Шесть малых медовух эйтра.", imageFile:"Minor_eitr_mead.png", source:item("minor-eitr-mead") },

    { slug:"black-forge", type:"item", category:"building", en:"Black Forge", ru:"Чёрная кузница", descriptionEn:"The main Mistlands crafting station.", descriptionRu:"Основная ремесленная станция Туманных земель.", imageFile:"Black_forge.png", source:building("black-forge") },
    { slug:"galdr-table", type:"item", category:"building", en:"Galdr Table", ru:"Стол гальдра", descriptionEn:"The crafting station for eitr magic.", descriptionRu:"Ремесленная станция для магии эйтра.", imageFile:"Galdr_table.png", source:building("galdr-table") },
    { slug:"eitr-refinery", type:"item", category:"building", en:"Eitr Refinery", ru:"Эйтровый очиститель", descriptionEn:"Refines sap and soft tissue into refined eitr.", descriptionRu:"Перерабатывает сок и мягкую ткань в очищенный эйтр.", imageFile:"Eitr_refinery.png", source:building("eitr-refinery") },
    { slug:"sap-extractor", type:"item", category:"building", en:"Sap Extractor", ru:"Экстрактор сока", descriptionEn:"Extracts sap from ancient Yggdrasil roots.", descriptionRu:"Извлекает сок из древних корней Иггдрасиля.", imageFile:"Sap_extractor.png", source:building("sap-extractor") },
    { slug:"black-forge-cooler", type:"item", category:"building", en:"Black Forge Cooler", ru:"Охладитель чёрной кузницы", descriptionEn:"An upgrade for the Black Forge.", descriptionRu:"Улучшение Чёрной кузницы.", imageFile:"Black_forge_cooler.png", source:building("black-forge-cooler") },
    { slug:"vice", type:"item", category:"building", en:"Vice", ru:"Тиски", descriptionEn:"An additional Black Forge upgrade.", descriptionRu:"Дополнительное улучшение Чёрной кузницы.", imageFile:"Vice.png", source:building("vice") },
    { slug:"rune-table", type:"item", category:"building", en:"Rune Table", ru:"Рунный стол", descriptionEn:"An upgrade for the Galdr Table.", descriptionRu:"Улучшение Стола гальдра.", imageFile:"Rune_table.png", source:building("rune-table") },
    { slug:"mortar-and-pestle", type:"item", category:"building", en:"Mortar and Pestle", ru:"Ступка и пестик", descriptionEn:"A Cauldron upgrade for Mistlands cooking.", descriptionRu:"Улучшение котла для кухни Туманных земель.", imageFile:"Mortar_and_pestle.png", source:building("mortar-and-pestle") },
    { slug:"wisp-fountain", type:"item", category:"building", en:"Wisp Fountain", ru:"Фонтан огоньков", descriptionEn:"Attracts wisps at night.", descriptionRu:"Привлекает огоньки ночью.", imageFile:"Wisp_fountain.png", source:building("wisp-fountain") }
  ],
  recipes: [
    { item:"refined-eitr", station:"eitr-refinery", ingredients:[["sap",1],["soft-tissue",1]] },
    { item:"mechanical-spring", station:"artisan-table", ingredients:[["refined-eitr",1],["iron",3]] },

    { item:"mistwalker", station:"black-forge", ingredients:[["finewood",3],["iron",15],["refined-eitr",10],["wisp",3]] },
    { item:"jotun-bane", station:"black-forge", ingredients:[["yggdrasil-wood",5],["iron",15],["bilebag",3],["refined-eitr",10]] },
    { item:"demolisher", station:"black-forge", ingredients:[["yggdrasil-wood",10],["iron",20],["refined-eitr",10]] },
    { item:"skull-splittur", station:"black-forge", ingredients:[["iron",30],["yggdrasil-wood",15],["refined-eitr",10]] },
    { item:"krom", station:"black-forge", ingredients:[["iron",30],["bronze",20],["scale-hide",5]] },
    { item:"himminafl", station:"black-forge", ingredients:[["yggdrasil-wood",10],["refined-eitr",15],["silver",5],["mandible",2]] },
    { item:"carapace-spear", station:"black-forge", ingredients:[["yggdrasil-wood",10],["carapace",4],["mandible",2]] },
    { item:"spinesnap", station:"black-forge", ingredients:[["finewood",10],["bone-fragments",40],["refined-eitr",10]] },
    { item:"arbalest", station:"black-forge", ingredients:[["wood",10],["iron",8],["root",4]] },
    { item:"skoll-and-hati", station:"black-forge", ingredients:[["finewood",4],["iron",10],["black-metal",10]] },
    { item:"carapace-shield", station:"black-forge", ingredients:[["carapace",20],["scale-hide",3],["refined-eitr",10]] },
    { item:"carapace-buckler", station:"black-forge", ingredients:[["carapace",16],["scale-hide",3],["refined-eitr",10]] },
    { item:"black-metal-pickaxe", station:"forge", level:2, ingredients:[["yggdrasil-wood",3],["black-metal",25]] },
    { item:"grappling-hook", station:"black-forge", ingredients:[["yggdrasil-wood",10],["refined-eitr",10],["mandible",4],["hook",1]] },
    { item:"bile-bomb-x3", station:"workbench", output:3, ingredients:[["sap",1],["bilebag",1],["resin",3]] },

    { item:"staff-of-embers", station:"galdr-table", ingredients:[["yggdrasil-wood",20],["surtling-core",4],["refined-eitr",16]] },
    { item:"staff-of-frost", station:"galdr-table", ingredients:[["yggdrasil-wood",20],["freeze-gland",4],["refined-eitr",16]] },
    { item:"staff-of-protection", station:"galdr-table", ingredients:[["yggdrasil-wood",20],["blood-clot",4],["refined-eitr",16]] },
    { item:"dead-raiser", station:"galdr-table", ingredients:[["bone-fragments",10],["refined-eitr",16],["skeleton-trophy",4]] },

    { item:"carapace-helmet", station:"black-forge", ingredients:[["carapace",16],["scale-hide",3],["mandible",2],["refined-eitr",4]] },
    { item:"carapace-breastplate", station:"black-forge", ingredients:[["carapace",20],["scale-hide",3],["iron",5],["refined-eitr",4]] },
    { item:"carapace-greaves", station:"black-forge", ingredients:[["carapace",20],["scale-hide",3],["iron",5],["refined-eitr",4]] },
    { item:"eitr-weave-hood", station:"galdr-table", ingredients:[["linen-thread",16],["refined-eitr",15],["iron",2]] },
    { item:"eitr-weave-robe", station:"galdr-table", ingredients:[["linen-thread",20],["refined-eitr",20],["feathers",10],["scale-hide",5]] },
    { item:"eitr-weave-trousers", station:"galdr-table", ingredients:[["linen-thread",20],["refined-eitr",20],["scale-hide",10]] },
    { item:"feather-cape", station:"galdr-table", ingredients:[["feathers",10],["scale-hide",5],["refined-eitr",20]] },

    { item:"pulsating-earrings", station:"black-forge", ingredients:[["carapace",5],["refined-eitr",5],["gjall-trophy",1]] },
    { item:"resounding-shackle", station:"black-forge", ingredients:[["refined-eitr",5],["scale-hide",5],["mandible",1],["seeker-trophy",1]] },

    { item:"sealbreaker", station:"galdr-table", ingredients:[["sealbreaker-fragment",9]] },
    { item:"wisplight", station:"workbench", ingredients:[["silver",1],["wisp",1]] },

    { item:"cooked-seeker-meat", station:"iron-cooking-station", ingredients:[["seeker-meat",1]] },
    { item:"cooked-hare-meat", station:"iron-cooking-station", ingredients:[["hare-meat",1]] },
    { item:"cooked-chicken-meat", station:"iron-cooking-station", ingredients:[["chicken-meat",1]] },
    { item:"cooked-egg", station:"cauldron", level:5, ingredients:[["egg",1]] },
    { item:"seeker-aspic-x2", station:"cauldron", level:5, output:2, ingredients:[["seeker-meat",2],["magecap",2],["royal-jelly",2]] },
    { item:"yggdrasil-porridge", station:"cauldron", level:5, ingredients:[["sap",4],["barley",3],["royal-jelly",2]] },
    { item:"mushroom-omelette", station:"cauldron", level:5, ingredients:[["egg",3],["jotun-puffs",3]] },
    { item:"salad-x3", station:"cauldron", level:5, output:3, ingredients:[["jotun-puffs",3],["onion",3],["cloudberries",3]] },
    { item:"uncooked-misthare-supreme", station:"food-preparation-table", ingredients:[["hare-meat",1],["jotun-puffs",3],["carrot",2]] },
    { item:"misthare-supreme", station:"stone-oven", ingredients:[["uncooked-misthare-supreme",1]] },
    { item:"uncooked-meat-platter", station:"food-preparation-table", ingredients:[["seeker-meat",1],["lox-meat",1],["hare-meat",1]] },
    { item:"meat-platter", station:"stone-oven", ingredients:[["uncooked-meat-platter",1]] },
    { item:"uncooked-honey-glazed-chicken", station:"food-preparation-table", ingredients:[["chicken-meat",1],["honey",3],["jotun-puffs",2]] },
    { item:"honey-glazed-chicken", station:"stone-oven", ingredients:[["uncooked-honey-glazed-chicken",1]] },
    { item:"uncooked-stuffed-mushroom", station:"food-preparation-table", ingredients:[["magecap",3],["blood-clot",1],["turnip",2]] },
    { item:"stuffed-mushroom", station:"stone-oven", ingredients:[["uncooked-stuffed-mushroom",1]] },

    { item:"mead-base-major-healing", station:"mead-ketill", ingredients:[["honey",10],["blood-clot",4],["royal-jelly",5]] },
    { item:"major-healing-mead-x6", station:"fermenter", output:6, ingredients:[["mead-base-major-healing",1]] },
    { item:"mead-base-lingering-stamina", station:"mead-ketill", ingredients:[["sap",10],["cloudberries",10],["jotun-puffs",10]] },
    { item:"lingering-stamina-mead-x6", station:"fermenter", output:6, ingredients:[["mead-base-lingering-stamina",1]] },
    { item:"mead-base-minor-eitr", station:"mead-ketill", ingredients:[["honey",10],["sap",5],["jotun-puffs",2],["magecap",5]] },
    { item:"minor-eitr-mead-x6", station:"fermenter", output:6, ingredients:[["mead-base-minor-eitr",1]] },

    { item:"black-forge", station:"hammer", ingredients:[["black-marble",10],["yggdrasil-wood",10],["black-core",5]] },
    { item:"galdr-table", station:"hammer", ingredients:[["yggdrasil-wood",20],["black-metal",10],["black-core",5],["refined-eitr",5]] },
    { item:"eitr-refinery", station:"hammer", ingredients:[["black-marble",20],["black-metal",5],["yggdrasil-wood",10],["black-core",5],["sap",3]] },
    { item:"sap-extractor", station:"hammer", ingredients:[["yggdrasil-wood",10],["black-metal",5],["dvergr-extractor",1]] },
    { item:"black-forge-cooler", station:"hammer", ingredients:[["iron",5],["copper",5],["black-marble",4]] },
    { item:"vice", station:"hammer", ingredients:[["iron",5],["copper",8],["mechanical-spring",2]] },
    { item:"rune-table", station:"hammer", ingredients:[["black-marble",10],["yggdrasil-wood",5],["refined-eitr",10]] },
    { item:"mortar-and-pestle", station:"hammer", ingredients:[["black-marble",8],["finewood",6],["corewood",4]] },
    { item:"wisp-fountain", station:"hammer", ingredients:[["stone",10],["torn-spirit",1]] }
  ],
  upgrades: [
    { item:"mistwalker", level:2, stationLevel:2, ingredients:[["iron",10],["refined-eitr",5],["wisp",1]] },
    { item:"mistwalker", level:3, stationLevel:3, ingredients:[["iron",20],["refined-eitr",10],["wisp",2]] },
    { item:"mistwalker", level:4, stationLevel:4, ingredients:[["iron",40],["refined-eitr",20],["wisp",4]] },

    { item:"jotun-bane", level:2, stationLevel:2, ingredients:[["iron",10],["bilebag",1],["refined-eitr",1]] },
    { item:"jotun-bane", level:3, stationLevel:3, ingredients:[["iron",20],["bilebag",2],["refined-eitr",2]] },
    { item:"jotun-bane", level:4, stationLevel:4, ingredients:[["iron",40],["bilebag",4],["refined-eitr",4]] },

    { item:"demolisher", level:2, stationLevel:2, ingredients:[["yggdrasil-wood",2],["iron",15],["refined-eitr",2]] },
    { item:"demolisher", level:3, stationLevel:3, ingredients:[["yggdrasil-wood",4],["iron",30],["refined-eitr",4]] },
    { item:"demolisher", level:4, stationLevel:4, ingredients:[["yggdrasil-wood",8],["iron",60],["refined-eitr",8]] },

    { item:"skull-splittur", level:2, stationLevel:2, ingredients:[["iron",15],["yggdrasil-wood",5]] },
    { item:"skull-splittur", level:3, stationLevel:3, ingredients:[["iron",30],["yggdrasil-wood",10]] },
    { item:"skull-splittur", level:4, stationLevel:4, ingredients:[["iron",60],["yggdrasil-wood",20]] },

    { item:"krom", level:2, stationLevel:2, ingredients:[["iron",15],["bronze",10],["scale-hide",5]] },
    { item:"krom", level:3, stationLevel:3, ingredients:[["iron",30],["bronze",20],["scale-hide",10]] },
    { item:"krom", level:4, stationLevel:4, ingredients:[["iron",60],["bronze",40],["scale-hide",20]] },

    { item:"himminafl", level:2, stationLevel:2, ingredients:[["refined-eitr",15],["silver",5],["mandible",2]] },
    { item:"himminafl", level:3, stationLevel:3, ingredients:[["refined-eitr",30],["silver",10],["mandible",4]] },
    { item:"himminafl", level:4, stationLevel:4, ingredients:[["refined-eitr",60],["silver",20],["mandible",8]] },

    { item:"carapace-spear", level:2, stationLevel:2, ingredients:[["yggdrasil-wood",5],["carapace",4],["mandible",1]] },
    { item:"carapace-spear", level:3, stationLevel:3, ingredients:[["yggdrasil-wood",10],["carapace",8],["mandible",2]] },
    { item:"carapace-spear", level:4, stationLevel:4, ingredients:[["yggdrasil-wood",20],["carapace",16],["mandible",4]] },

    { item:"spinesnap", level:2, stationLevel:2, ingredients:[["finewood",5],["bone-fragments",20]] },
    { item:"spinesnap", level:3, stationLevel:3, ingredients:[["finewood",10],["bone-fragments",40]] },
    { item:"spinesnap", level:4, stationLevel:4, ingredients:[["finewood",20],["bone-fragments",80]] },

    { item:"arbalest", level:2, stationLevel:2, ingredients:[["wood",5],["iron",4],["root",1]] },
    { item:"arbalest", level:3, stationLevel:3, ingredients:[["wood",10],["iron",8],["root",2]] },
    { item:"arbalest", level:4, stationLevel:4, ingredients:[["wood",20],["iron",16],["root",4]] },

    { item:"skoll-and-hati", level:2, stationLevel:2, ingredients:[["iron",4],["black-metal",4]] },
    { item:"skoll-and-hati", level:3, stationLevel:3, ingredients:[["iron",8],["black-metal",8]] },
    { item:"skoll-and-hati", level:4, stationLevel:4, ingredients:[["iron",16],["black-metal",16]] },

    { item:"black-metal-pickaxe", level:2, stationLevel:3, ingredients:[["yggdrasil-wood",1],["black-metal",15]] },
    { item:"black-metal-pickaxe", level:3, stationLevel:4, ingredients:[["yggdrasil-wood",2],["black-metal",30]] },
    { item:"black-metal-pickaxe", level:4, stationLevel:5, ingredients:[["yggdrasil-wood",4],["black-metal",60]] },

    ...["staff-of-embers","staff-of-frost"].flatMap((itemSlug) => [
      { item:itemSlug, level:2, stationLevel:2, ingredients:[["yggdrasil-wood",10],[itemSlug === "staff-of-embers" ? "surtling-core" : "freeze-gland",2],["refined-eitr",8]] as Array<[string,number]> },
      { item:itemSlug, level:3, stationLevel:3, ingredients:[["yggdrasil-wood",20],[itemSlug === "staff-of-embers" ? "surtling-core" : "freeze-gland",4],["refined-eitr",16]] as Array<[string,number]> },
      { item:itemSlug, level:4, stationLevel:4, ingredients:[["yggdrasil-wood",40],[itemSlug === "staff-of-embers" ? "surtling-core" : "freeze-gland",8],["refined-eitr",32]] as Array<[string,number]> }
    ]),
    { item:"staff-of-protection", level:2, stationLevel:2, ingredients:[["yggdrasil-wood",10],["blood-clot",2],["refined-eitr",8]] },
    { item:"staff-of-protection", level:3, stationLevel:3, ingredients:[["yggdrasil-wood",20],["blood-clot",4],["refined-eitr",16]] },
    { item:"staff-of-protection", level:4, stationLevel:4, ingredients:[["yggdrasil-wood",40],["blood-clot",8],["refined-eitr",32]] },
    { item:"dead-raiser", level:2, stationLevel:2, ingredients:[["bone-fragments",5],["refined-eitr",8],["skeleton-trophy",2]] },
    { item:"dead-raiser", level:3, stationLevel:3, ingredients:[["bone-fragments",10],["refined-eitr",16],["skeleton-trophy",4]] },
    { item:"dead-raiser", level:4, stationLevel:4, ingredients:[["bone-fragments",20],["refined-eitr",32],["skeleton-trophy",8]] },

    { item:"carapace-shield", level:2, stationLevel:2, ingredients:[["carapace",10],["scale-hide",3],["refined-eitr",3]] },
    { item:"carapace-shield", level:3, stationLevel:3, ingredients:[["carapace",20],["scale-hide",6],["refined-eitr",6]] },
    { item:"carapace-buckler", level:2, stationLevel:2, ingredients:[["carapace",8],["scale-hide",3],["refined-eitr",3]] },
    { item:"carapace-buckler", level:3, stationLevel:3, ingredients:[["carapace",16],["scale-hide",6],["refined-eitr",6]] },

    { item:"carapace-helmet", level:2, stationLevel:2, ingredients:[["carapace",8],["scale-hide",1],["refined-eitr",2]] },
    { item:"carapace-helmet", level:3, stationLevel:3, ingredients:[["carapace",16],["scale-hide",2],["refined-eitr",4]] },
    { item:"carapace-helmet", level:4, stationLevel:4, ingredients:[["carapace",32],["scale-hide",4],["refined-eitr",8]] },
    ...["carapace-breastplate","carapace-greaves"].flatMap((itemSlug) => [
      { item:itemSlug, level:2, stationLevel:2, ingredients:[["carapace",10],["scale-hide",1],["refined-eitr",2]] as Array<[string,number]> },
      { item:itemSlug, level:3, stationLevel:3, ingredients:[["carapace",20],["scale-hide",2],["refined-eitr",4]] as Array<[string,number]> },
      { item:itemSlug, level:4, stationLevel:4, ingredients:[["carapace",40],["scale-hide",4],["refined-eitr",8]] as Array<[string,number]> }
    ]),

    { item:"eitr-weave-hood", level:2, stationLevel:2, ingredients:[["linen-thread",8],["refined-eitr",5]] },
    { item:"eitr-weave-hood", level:3, stationLevel:3, ingredients:[["linen-thread",16],["refined-eitr",10]] },
    { item:"eitr-weave-hood", level:4, stationLevel:4, ingredients:[["linen-thread",32],["refined-eitr",20]] },
    ...["eitr-weave-robe","eitr-weave-trousers"].flatMap((itemSlug) => [
      { item:itemSlug, level:2, stationLevel:2, ingredients:[["linen-thread",10],["refined-eitr",5]] as Array<[string,number]> },
      { item:itemSlug, level:3, stationLevel:3, ingredients:[["linen-thread",20],["refined-eitr",10]] as Array<[string,number]> },
      { item:itemSlug, level:4, stationLevel:4, ingredients:[["linen-thread",40],["refined-eitr",20]] as Array<[string,number]> }
    ])
  ],
  stats: [
    ["mistwalker","slash_damage","75"],["mistwalker","frost_damage","40"],["mistwalker","spirit_damage","15"],["mistwalker","durability","200"],
    ["jotun-bane","slash_damage","80"],["jotun-bane","chop","70"],["jotun-bane","poison_damage","40"],["jotun-bane","durability","250"],
    ["demolisher","blunt_damage","145"],["demolisher","durability","250"],
    ["skull-splittur","slash_damage","130"],["skull-splittur","chop","70"],["skull-splittur","durability","200"],
    ["krom","slash_damage","150"],["krom","durability","250"],
    ["himminafl","pierce_damage","85"],["himminafl","lightning_damage","40"],["himminafl","durability","250"],
    ["carapace-spear","pierce_damage","115"],["carapace-spear","durability","250"],
    ["spinesnap","pierce_damage","72"],["spinesnap","spirit_damage","5"],["spinesnap","durability","250"],
    ["arbalest","pierce_damage","200"],["arbalest","durability","150"],
    ["skoll-and-hati","slash_damage","45"],["skoll-and-hati","pierce_damage","45"],["skoll-and-hati","durability","250"],
    ["carapace-shield","block_armor","96"],["carapace-shield","durability","250"],
    ["carapace-buckler","block_armor","78"],["carapace-buckler","durability","250"],
    ["black-metal-pickaxe","pierce_damage","49"],["black-metal-pickaxe","pickaxe","49"],["black-metal-pickaxe","durability","210"],
    ["grappling-hook","pierce_damage","10"],["grappling-hook","durability","300"],
    ["staff-of-embers","blunt_damage","120"],["staff-of-embers","fire_damage","120"],["staff-of-embers","durability","200"],
    ["staff-of-frost","frost_damage","30"],["staff-of-frost","durability","200"],
    ["staff-of-protection","durability","200"],["dead-raiser","durability","200"],

    ["carapace-helmet","armor","32"],["carapace-breastplate","armor","32"],["carapace-greaves","armor","32"],
    ["eitr-weave-hood","armor","16"],["eitr-weave-robe","armor","16"],["eitr-weave-trousers","armor","16"],["feather-cape","armor","1"],
    ["pulsating-earrings","adrenaline","65"],["pulsating-earrings","duration","60","s"],
    ["resounding-shackle","adrenaline","75"],["resounding-shackle","duration","60","s"],

    ["seeker-aspic-x2","health","28"],["seeker-aspic-x2","stamina","14"],["seeker-aspic-x2","eitr","85"],["seeker-aspic-x2","duration","30","min"],["seeker-aspic-x2","healing","3","hp/tick"],
    ["yggdrasil-porridge","health","27"],["yggdrasil-porridge","stamina","13"],["yggdrasil-porridge","eitr","80"],["yggdrasil-porridge","duration","25","min"],["yggdrasil-porridge","healing","3","hp/tick"],
    ["mushroom-omelette","health","28"],["mushroom-omelette","stamina","85"],["mushroom-omelette","duration","25","min"],["mushroom-omelette","healing","3","hp/tick"],
    ["salad-x3","health","26"],["salad-x3","stamina","80"],["salad-x3","duration","25","min"],["salad-x3","healing","3","hp/tick"],
    ["misthare-supreme","health","85"],["misthare-supreme","stamina","28"],["misthare-supreme","duration","25","min"],["misthare-supreme","healing","5","hp/tick"],
    ["meat-platter","health","80"],["meat-platter","stamina","26"],["meat-platter","duration","30","min"],["meat-platter","healing","5","hp/tick"],
    ["honey-glazed-chicken","health","80"],["honey-glazed-chicken","stamina","26"],["honey-glazed-chicken","duration","30","min"],["honey-glazed-chicken","healing","5","hp/tick"],
    ["stuffed-mushroom","health","25"],["stuffed-mushroom","stamina","12"],["stuffed-mushroom","eitr","75"],["stuffed-mushroom","duration","25","min"],["stuffed-mushroom","healing","3","hp/tick"]
  ],
  resourceSources: [
    ["wisp","Gather from a Wisp Fountain at night.","Собирается ночью у фонтана огоньков.",item("wisp")],
    ["yggdrasil-wood","Chop Yggdrasil shoots in the Mistlands with a strong axe.","Рубите побеги Иггдрасиля в Туманных землях мощным топором.",item("yggdrasil-wood")],
    ["black-marble","Mine petrified giant remains or dismantle Dvergr black-marble structures.","Добывайте окаменевшие останки гигантов или разбирайте постройки двергов.",item("black-marble")],
    ["black-core","Found mainly in Infested Mines.","Находится главным образом в Заражённых шахтах.",item("black-core")],
    ["soft-tissue","Mine petrified skulls and loot Dvergr structures.","Добывайте окаменевшие черепа и обыскивайте постройки двергов.",item("soft-tissue")],
    ["sap","Extract from Yggdrasil roots using a Sap Extractor.","Извлекается из корней Иггдрасиля экстрактором сока.",item("sap")],
    ["refined-eitr","Refine Sap and Soft Tissue in an Eitr Refinery.","Перерабатывайте сок и мягкую ткань в Эйтровом очистителе.",item("refined-eitr")],
    ["carapace","Dropped by Seekers and Seeker Soldiers.","Выпадает из Искателей и Искателей-солдат.",item("carapace")],
    ["mandible","Dropped by Seeker Soldiers.","Выпадает из Искателей-солдат.",item("mandible")],
    ["blood-clot","Dropped by Ticks.","Выпадает из клещей.",item("blood-clot")],
    ["bilebag","Dropped by Gjalls.","Выпадает из гьяллов.",item("bilebag")],
    ["royal-jelly","Gathered in Infested Mines.","Собирается в Заражённых шахтах.",item("royal-jelly")],
    ["dvergr-extractor","Recovered from protected Dvergr component crates.","Добывается из защищённых компонентных ящиков двергов.",item("dvergr-extractor")],
    ["sealbreaker-fragment","Found by destroying crystal altars in Infested Mines.","Находится при разрушении кристальных алтарей в Заражённых шахтах.",item("sealbreaker-fragment")],
    ["hook","Found in Dvergr treasure chests in ruined guard towers.","Находится в сокровищницах разрушенных сторожевых башен двергов.",item("hook")],
    ["black-marble-battle-idol","Rare Mistlands treasure used at the Forge of Potential.","Редкая добыча Туманных земель для Кузницы потенциала.",item("black-marble-battle-idol")],
    ["black-marble-protection-idol","Rare Mistlands treasure used at the Forge of Potential.","Редкая добыча Туманных земель для Кузницы потенциала.",item("black-marble-protection-idol")],
    ["torn-spirit","Dropped by Yagluth after defeating the Plains boss; used to build a Wisp Fountain.","Выпадает после победы над Яглутом; используется для Фонтана огоньков.",item("torn-spirit")],
    ["scale-hide","Dropped by Hares at 100%, 1–3 per normal Hare.","Гарантированно выпадает из зайцев, по 1–3.",item("scale-hide")],
    ["seeker-meat","Dropped by Seekers and Seeker Soldiers at 100%, normally 1–2.","Гарантированно выпадает из Искателей и Искателей-солдат, обычно по 1–2.",item("seeker-meat")],
    ["hare-meat","Dropped by Hares at 100%, 1 per normal Hare.","Гарантированно выпадает из зайцев, по 1.",item("hare-meat")],
    ["chicken-meat","Obtained by slaughtering adult poultry raised from Eggs.","Получается при забое взрослой домашней птицы, выращенной из яиц.",item("chicken-meat")],
    ["egg","Buy the first Eggs from Haldor after Yagluth; fed adult hens can lay more Eggs.","Первые яйца покупаются у Хальдора после Яглута; накормленные взрослые куры несут новые яйца.",item("egg")],
    ["magecap","Pick wild Magecaps in the Mistlands and cultivate them there with a Cultivator.","Собирайте дикие Магические грибы в Туманных землях и выращивайте там культиватором.",item("magecap")],
    ["jotun-puffs","Pick wild Jotun Puffs in the Mistlands and cultivate them there with a Cultivator.","Собирайте дикие Йотунские пуховики в Туманных землях и выращивайте там культиватором.",item("jotun-puffs")],
    ["mechanical-spring","Craft at the Artisan Table from 3 Iron + 1 Refined Eitr.","Создаётся на Столе ремесленника из 3 железа и 1 очищенного эйтра.",item("mechanical-spring")],
    ["gjall-trophy","Dropped by Gjall at 30%.","Выпадает из Гьялла с шансом 30%.",item("gjall-trophy")],
    ["seeker-trophy","Dropped by Seekers at 5%.","Выпадает из Искателей с шансом 5%.",item("seeker-trophy")]
  ]
};

export const ensureMistlandsCatalog = (env: Env): Promise<void> => applyCatalogSeed(env, mistlandsSeed);
