import type { Env } from "../env";
import { applyCatalogSeed, type CatalogSeed } from "./catalog-seed";

const item = (slug: string) => `https://www.valheim.tools/items/${slug}`;

const mountainSeed: CatalogSeed = {
  marker: "catalog_mountains_acquisition_v2_precision",
  biome: "mountains",
  replaceResourceSources: true,
  items: [
    { slug:"silver-ore", type:"resource", category:"material", en:"Silver Ore", ru:"Серебряная руда", descriptionEn:"Heavy ore mined from hidden silver veins in the Mountains.", descriptionRu:"Тяжёлая руда из скрытых серебряных жил в Горах.", imageFile:"Silver_ore.png", source:item("silver-ore") },
    { slug:"silver", type:"resource", category:"material", en:"Silver", ru:"Серебро", descriptionEn:"Silver ingot smelted from silver ore.", descriptionRu:"Серебряный слиток, выплавляемый из серебряной руды.", imageFile:"Silver.png", source:item("silver") },
    { slug:"obsidian", type:"resource", category:"material", en:"Obsidian", ru:"Обсидиан", descriptionEn:"Black volcanic glass mined from Mountain deposits.", descriptionRu:"Чёрное вулканическое стекло из горных залежей.", imageFile:"Obsidian.png", source:item("obsidian") },
    { slug:"crystal", type:"resource", category:"material", en:"Crystal", ru:"Кристалл", descriptionEn:"Clear crystal dropped by Stone Golems.", descriptionRu:"Прозрачный кристалл, выпадающий из каменных големов.", imageFile:"Crystal.png", source:item("crystal") },
    { slug:"freeze-gland", type:"resource", category:"material", en:"Freeze Gland", ru:"Морозная железа", descriptionEn:"An icy organ dropped by Drakes.", descriptionRu:"Ледяная железа, выпадающая из драконов.", imageFile:"Freeze_gland.png", source:item("freeze-gland") },
    { slug:"wolf-fang", type:"resource", category:"material", en:"Wolf Fang", ru:"Волчий клык", descriptionEn:"A sharp fang dropped by Wolves.", descriptionRu:"Острый клык, выпадающий из волков.", imageFile:"Wolf_fang.png", source:item("wolf-fang") },
    { slug:"wolf-pelt", type:"resource", category:"material", en:"Wolf Pelt", ru:"Волчья шкура", descriptionEn:"Warm hide taken from Mountain wolves.", descriptionRu:"Тёплая шкура горных волков.", imageFile:"Wolf_pelt.png", source:item("wolf-pelt") },
    { slug:"wolf-meat", type:"resource", category:"material", en:"Wolf Meat", ru:"Волчье мясо", descriptionEn:"Raw meat dropped by Wolves.", descriptionRu:"Сырое мясо, выпадающее из волков.", imageFile:"Wolf_meat.png", source:item("wolf-meat") },
    { slug:"onion-seeds", type:"resource", category:"material", en:"Onion Seeds", ru:"Семена лука", descriptionEn:"Seeds found in Mountain chests and grown into onions.", descriptionRu:"Семена из горных сундуков, из которых выращивается лук.", imageFile:"Onion_seeds.png", source:item("onion-seeds") },
    { slug:"onion", type:"resource", category:"material", en:"Onion", ru:"Лук", descriptionEn:"A farm crop grown from onion seeds.", descriptionRu:"Фермерская культура, выращиваемая из семян лука.", imageFile:"Onion.png", source:item("onion") },
    { slug:"dragon-egg", type:"resource", category:"material", en:"Dragon Egg", ru:"Драконье яйцо", descriptionEn:"A massive egg used to summon Moder.", descriptionRu:"Огромное яйцо для призыва Моудер.", imageFile:"Dragon_egg.png", source:item("dragon-egg") },
    { slug:"drake-trophy", type:"resource", category:"trophy", en:"Drake Trophy", ru:"Трофей: дракон", descriptionEn:"A rare trophy from Drakes.", descriptionRu:"Редкий трофей с драконов.", imageFile:"Drake_trophy.png", source:item("drake-trophy") },
    { slug:"wolf-trophy", type:"resource", category:"trophy", en:"Wolf Trophy", ru:"Трофей: волк", descriptionEn:"A trophy from Wolves.", descriptionRu:"Трофей с волков.", imageFile:"Wolf_trophy.png", source:item("wolf-trophy") },
    { slug:"fenring-trophy", type:"resource", category:"trophy", en:"Fenring Trophy", ru:"Трофей: фенринг", descriptionEn:"A trophy from Fenrings.", descriptionRu:"Трофей с фенрингов.", imageFile:"Fenring_trophy.png", source:item("fenring-trophy") },
    { slug:"stone-golem-trophy", type:"resource", category:"trophy", en:"Stone Golem Trophy", ru:"Трофей: каменный голем", descriptionEn:"A heavy trophy from Stone Golems.", descriptionRu:"Тяжёлый трофей с каменных големов.", imageFile:"Stone_Golem_trophy.png", source:item("stone-golem-trophy") },
    { slug:"fenris-hair", type:"resource", category:"material", en:"Fenris Hair", ru:"Волосы Фенриса", descriptionEn:"Thick hair gathered inside Frost Caves.", descriptionRu:"Густая шерсть, добываемая в Ледяных пещерах.", imageFile:"Fenris_hair.png", source:item("fenris-hair") },
    { slug:"fenris-claw", type:"resource", category:"material", en:"Fenris Claw", ru:"Коготь Фенриса", descriptionEn:"A hard claw found in Frost Caves.", descriptionRu:"Твёрдый коготь из Ледяных пещер.", imageFile:"Fenris_claw.png", source:item("fenris-claw") },
    { slug:"cultist-trophy", type:"resource", category:"trophy", en:"Cultist Trophy", ru:"Трофей: культист", descriptionEn:"A trophy dropped by Cultists in Frost Caves.", descriptionRu:"Трофей с культистов в Ледяных пещерах.", imageFile:"Cultist_trophy.png", source:item("cultist-trophy") },
    { slug:"silver-battle-idol", type:"resource", category:"material", en:"Silver Battle Idol", ru:"Серебряный боевой идол", descriptionEn:"Mountain-tier Forge of Potential material for weapons.", descriptionRu:"Горный материал для улучшения оружия в Кузнице потенциала.", imageFile:"Silver_Battle_Idol.png", source:item("silver-battle-idol") },
    { slug:"silver-protection-idol", type:"resource", category:"material", en:"Silver Protection Idol", ru:"Серебряный защитный идол", descriptionEn:"Mountain-tier Forge of Potential material for armour.", descriptionRu:"Горный материал для улучшения брони в Кузнице потенциала.", imageFile:"Silver_Protection_Idol.png", source:item("silver-protection-idol") },
    { slug:"scythe-handle", type:"resource", category:"material", en:"Scythe Handle", ru:"Рукоять косы", descriptionEn:"A sturdy handle sold by the Bog Witch after Moder is defeated.", descriptionRu:"Прочная рукоять, которую продаёт Болотная ведьма после победы над Моудер.", imageFile:"Scythe_handle.png", source:item("scythe-handle") },

    { slug:"crystal-battleaxe", type:"item", category:"weapon", en:"Crystal Battleaxe", ru:"Кристальная секира", descriptionEn:"A heavy silver-and-crystal battleaxe with spirit damage.", descriptionRu:"Тяжёлая секира из серебра и кристалла с духовным уроном.", imageFile:"Crystal_battleaxe.png", source:item("crystal-battleaxe") },
    { slug:"fang-spear", type:"item", category:"weapon", en:"Fang Spear", ru:"Копьё с клыком", descriptionEn:"A light Mountain spear tipped with a wolf fang.", descriptionRu:"Лёгкое горное копьё с волчьим клыком.", imageFile:"Fang_spear.png", source:item("fang-spear") },
    { slug:"silver-sword", type:"item", category:"weapon", en:"Silver Sword", ru:"Серебряный меч", descriptionEn:"A silver blade that also burns undead with spirit damage.", descriptionRu:"Серебряный клинок, наносящий нежити дополнительный духовный урон.", imageFile:"Silver_sword.png", source:item("silver-sword") },
    { slug:"frostner", type:"item", category:"weapon", en:"Frostner", ru:"Морознер", descriptionEn:"A silver mace that combines blunt, frost and spirit damage.", descriptionRu:"Серебряная булава с дробящим, морозным и духовным уроном.", imageFile:"Frostner.png", source:item("frostner") },
    { slug:"draugr-fang", type:"item", category:"weapon", en:"Draugr Fang", ru:"Клык драугра", descriptionEn:"A powerful bow that adds poison to every arrow.", descriptionRu:"Мощный лук, добавляющий яд к каждой стреле.", imageFile:"Draugr_Fang.png", source:item("draugr-fang") },
    { slug:"silver-knife", type:"item", category:"weapon", en:"Silver Knife", ru:"Серебряный нож", descriptionEn:"A fast silver knife with slash, pierce and spirit damage.", descriptionRu:"Быстрый серебряный нож с рубящим, колющим и духовным уроном.", imageFile:"Silver_knife.png", source:item("silver-knife") },
    { slug:"flesh-rippers", type:"item", category:"weapon", en:"Flesh Rippers", ru:"Разрыватели плоти", descriptionEn:"Fenris claws made into fast fist weapons.", descriptionRu:"Когти Фенриса, превращённые в быстрое кулачное оружие.", imageFile:"Flesh_rippers.png", source:item("flesh-rippers") },
    { slug:"silver-shield", type:"item", category:"weapon", en:"Silver Shield", ru:"Серебряный щит", descriptionEn:"A strong round silver shield built for blocking and parrying.", descriptionRu:"Крепкий круглый серебряный щит для блока и парирования.", imageFile:"Silver_shield.png", source:item("silver-shield") },
    { slug:"scythe", type:"item", category:"tool", en:"Scythe", ru:"Коса", descriptionEn:"A farming tool that harvests several ripe crops in one sweep.", descriptionRu:"Фермерский инструмент, срезающий сразу несколько созревших растений.", imageFile:"Scythe.png", source:item("scythe") },

    { slug:"obsidian-arrows-x20", type:"item", category:"weapon", en:"Obsidian Arrows ×20", ru:"Обсидиановые стрелы ×20", descriptionEn:"Twenty sharp obsidian arrows.", descriptionRu:"Двадцать острых обсидиановых стрел.", imageFile:"Obsidian_arrow.png", source:item("obsidian-arrow") },
    { slug:"frost-arrows-x20", type:"item", category:"weapon", en:"Frost Arrows ×20", ru:"Морозные стрелы ×20", descriptionEn:"Twenty arrows carrying frost damage.", descriptionRu:"Двадцать стрел с морозным уроном.", imageFile:"Frost_arrow.png", source:item("frost-arrow") },
    { slug:"poison-arrows-x20", type:"item", category:"weapon", en:"Poison Arrows ×20", ru:"Ядовитые стрелы ×20", descriptionEn:"Twenty arrows tipped with poison.", descriptionRu:"Двадцать стрел с ядовитыми наконечниками.", imageFile:"Poison_arrow.png", source:item("poison-arrow") },
    { slug:"silver-arrows-x20", type:"item", category:"weapon", en:"Silver Arrows ×20", ru:"Серебряные стрелы ×20", descriptionEn:"Twenty silver arrows with spirit damage.", descriptionRu:"Двадцать серебряных стрел с духовным уроном.", imageFile:"Silver_arrow.png", source:item("silver-arrow") },

    { slug:"drake-helmet", type:"item", category:"armor", en:"Drake Helmet", ru:"Драконий шлем", descriptionEn:"A finely forged silver helmet decorated with Drake trophies.", descriptionRu:"Серебряный шлем, украшенный трофеями драконов.", imageFile:"Drake_helmet.png", source:item("drake-helmet") },
    { slug:"wolf-hide-chestpiece", type:"item", category:"armor", en:"Wolf Hide Chestpiece", ru:"Нагрудник из волчьей шкуры", descriptionEn:"Heavy silver armour lined with warm wolf hide.", descriptionRu:"Тяжёлая серебряная броня с тёплой волчьей шкурой.", imageFile:"Wolf_armor_chest.png", source:item("wolf-hide-chestpiece") },
    { slug:"wolf-hide-trousers", type:"item", category:"armor", en:"Wolf Hide Trousers", ru:"Штаны из волчьей шкуры", descriptionEn:"Heavy silver leg armour made with wolf pelt and fangs.", descriptionRu:"Тяжёлая серебряная защита ног из волчьей шкуры и клыков.", imageFile:"Wolf_armor_legs.png", source:item("wolf-hide-trousers") },
    { slug:"wolf-fur-cape", type:"item", category:"armor", en:"Wolf Fur Cape", ru:"Плащ из волчьей шкуры", descriptionEn:"A warm cape that protects against the Mountain cold.", descriptionRu:"Тёплый плащ, защищающий от горного холода.", imageFile:"Wolf_fur_cape.png", source:item("wolf-fur-cape") },
    { slug:"fenris-hood", type:"item", category:"armor", en:"Fenris Hood", ru:"Капюшон Фенриса", descriptionEn:"A light Frost Cave hood with movement speed and Fenris set bonuses.", descriptionRu:"Лёгкий капюшон из Ледяных пещер с бонусом скорости и комплекта Фенриса.", imageFile:"Fenris_hood.png", source:item("fenris-hood") },
    { slug:"fenris-coat", type:"item", category:"armor", en:"Fenris Coat", ru:"Куртка Фенриса", descriptionEn:"Light frost-resistant armour that increases movement speed.", descriptionRu:"Лёгкая морозостойкая броня, повышающая скорость движения.", imageFile:"Fenris_coat.png", source:item("fenris-coat") },
    { slug:"fenris-leggings", type:"item", category:"armor", en:"Fenris Leggings", ru:"Поножи Фенриса", descriptionEn:"Light Fenris leg armour that increases movement speed.", descriptionRu:"Лёгкие поножи Фенриса, повышающие скорость движения.", imageFile:"Fenris_leggings.png", source:item("fenris-leggings") },

    { slug:"wolf-sight", type:"item", category:"trinket", en:"Wolf Sight", ru:"Волчий взор", descriptionEn:"A trinket that boosts Bows, Spears and pierce damage during its adrenaline surge.", descriptionRu:"Оберег, усиливающий луки, копья и колющий урон во время всплеска адреналина.", imageFile:"Wolf_Sight.png", source:item("wolf-sight") },
    { slug:"crystal-heart", type:"item", category:"trinket", en:"Crystal Heart", ru:"Кристальное сердце", descriptionEn:"A trinket that temporarily reduces incoming physical damage.", descriptionRu:"Оберег, временно уменьшающий входящий физический урон.", imageFile:"Crystal_Heart.png", source:item("crystal-heart") },

    { slug:"cooked-wolf-meat", type:"item", category:"food", en:"Cooked Wolf Meat", ru:"Жареное волчье мясо", descriptionEn:"Wolf meat cooked over a fire.", descriptionRu:"Волчье мясо, приготовленное на огне.", imageFile:"Cooked_wolf_meat.png", source:item("cooked-wolf-meat") },
    { slug:"wolf-jerky-x2", type:"item", category:"food", en:"Wolf Jerky ×2", ru:"Вяленое волчье мясо ×2", descriptionEn:"Two balanced portions of wolf jerky.", descriptionRu:"Две сбалансированные порции вяленого волчьего мяса.", imageFile:"Wolf_jerky.png", source:item("wolf-jerky") },
    { slug:"wolf-skewer", type:"item", category:"food", en:"Wolf Skewer", ru:"Волчий шашлык", descriptionEn:"A high-health skewer made with wolf meat, mushrooms and onion.", descriptionRu:"Сытный шашлык из волчьего мяса, грибов и лука.", imageFile:"Wolf_skewer.png", source:item("wolf-skewer") },
    { slug:"eyescream", type:"item", category:"food", en:"Eyescream", ru:"Глазомороженое", descriptionEn:"A cold stamina food made from greydwarf eyes and a freeze gland.", descriptionRu:"Холодная еда на выносливость из глаз грейдворфов и морозной железы.", imageFile:"Eyescream.png", source:item("eyescream") },
    { slug:"onion-soup", type:"item", category:"food", en:"Onion Soup", ru:"Луковый суп", descriptionEn:"A simple stamina-focused soup made from onions.", descriptionRu:"Простой суп из лука с упором на выносливость.", imageFile:"Onion_soup.png", source:item("onion-soup") }
  ],
  recipes: [
    { item:"silver", station:"smelter", ingredients:[["silver-ore",1]] },
    { item:"crystal-battleaxe", station:"forge", level:3, ingredients:[["ancient-bark",40],["silver",30],["crystal",10]] },
    { item:"fang-spear", station:"forge", level:3, ingredients:[["ancient-bark",10],["wolf-fang",4],["leather-scraps",2],["silver",2]] },
    { item:"silver-sword", station:"forge", level:3, ingredients:[["wood",2],["silver",40],["iron",5],["leather-scraps",3]] },
    { item:"frostner", station:"forge", level:3, ingredients:[["ancient-bark",10],["silver",30],["ymir-flesh",5],["freeze-gland",5]] },
    { item:"draugr-fang", station:"forge", level:2, ingredients:[["ancient-bark",10],["silver",20],["deer-hide",2],["guck",10]] },
    { item:"silver-knife", station:"forge", level:3, ingredients:[["wood",2],["silver",10],["leather-scraps",3],["iron",2]] },
    { item:"flesh-rippers", station:"forge", level:3, ingredients:[["fenris-hair",10],["fenris-claw",6],["silver",10]] },
    { item:"silver-shield", station:"forge", level:3, ingredients:[["finewood",10],["silver",8]] },
    { item:"scythe", station:"forge", level:2, ingredients:[["scythe-handle",1],["silver",6]] },

    { item:"obsidian-arrows-x20", station:"workbench", level:3, output:20, ingredients:[["wood",8],["obsidian",4],["feathers",2]] },
    { item:"frost-arrows-x20", station:"workbench", level:4, output:20, ingredients:[["wood",8],["obsidian",4],["feathers",2],["freeze-gland",1]] },
    { item:"poison-arrows-x20", station:"workbench", level:3, output:20, ingredients:[["wood",8],["obsidian",4],["feathers",2],["ooze",2]] },
    { item:"silver-arrows-x20", station:"forge", level:3, output:20, ingredients:[["wood",8],["silver",1],["feathers",2]] },

    { item:"drake-helmet", station:"forge", ingredients:[["silver",20],["wolf-pelt",2],["drake-trophy",2]] },
    { item:"wolf-hide-chestpiece", station:"forge", level:2, ingredients:[["silver",20],["wolf-pelt",5],["chain",1]] },
    { item:"wolf-hide-trousers", station:"forge", level:2, ingredients:[["silver",20],["wolf-pelt",5],["wolf-fang",4]] },
    { item:"wolf-fur-cape", station:"workbench", level:2, ingredients:[["wolf-pelt",6],["silver",4],["wolf-trophy",1]] },
    { item:"fenris-hood", station:"workbench", level:2, ingredients:[["fenris-hair",20],["wolf-pelt",2],["cultist-trophy",1]] },
    { item:"fenris-coat", station:"workbench", level:2, ingredients:[["fenris-hair",20],["wolf-pelt",5],["leather-scraps",10]] },
    { item:"fenris-leggings", station:"workbench", level:2, ingredients:[["fenris-hair",20],["wolf-pelt",5],["leather-scraps",10]] },

    { item:"wolf-sight", station:"forge", ingredients:[["silver",5],["wolf-fang",5],["fenring-trophy",1]] },
    { item:"crystal-heart", station:"forge", ingredients:[["silver",5],["crystal",5],["stone-golem-trophy",1]] },

    { item:"cooked-wolf-meat", station:"cooking-station", ingredients:[["wolf-meat",1]] },
    { item:"wolf-jerky-x2", station:"cauldron", level:3, output:2, ingredients:[["wolf-meat",1],["honey",1]] },
    { item:"wolf-skewer", station:"cauldron", level:3, ingredients:[["wolf-meat",1],["mushroom",2],["onion",1]] },
    { item:"eyescream", station:"cauldron", level:3, ingredients:[["greydwarf-eye",3],["freeze-gland",1]] },
    { item:"onion-soup", station:"cauldron", level:2, ingredients:[["onion",3]] }
  ],
  upgrades: [
    { item:"crystal-battleaxe", level:2, stationLevel:4, ingredients:[["ancient-bark",5],["silver",15]] },
    { item:"crystal-battleaxe", level:3, stationLevel:5, ingredients:[["ancient-bark",10],["silver",30]] },
    { item:"crystal-battleaxe", level:4, stationLevel:6, ingredients:[["ancient-bark",20],["silver",60]] },
    { item:"fang-spear", level:2, stationLevel:4, ingredients:[["ancient-bark",5],["wolf-fang",2],["leather-scraps",1],["silver",1]] },
    { item:"fang-spear", level:3, stationLevel:5, ingredients:[["ancient-bark",10],["wolf-fang",4],["leather-scraps",2],["silver",2]] },
    { item:"fang-spear", level:4, stationLevel:6, ingredients:[["ancient-bark",20],["wolf-fang",8],["leather-scraps",4],["silver",4]] },
    { item:"silver-sword", level:2, stationLevel:4, ingredients:[["wood",1],["silver",20],["leather-scraps",1],["iron",3]] },
    { item:"silver-sword", level:3, stationLevel:5, ingredients:[["wood",2],["silver",40],["leather-scraps",2],["iron",6]] },
    { item:"silver-sword", level:4, stationLevel:6, ingredients:[["wood",4],["silver",80],["leather-scraps",4],["iron",12]] },
    { item:"frostner", level:2, stationLevel:4, ingredients:[["silver",15]] },
    { item:"frostner", level:3, stationLevel:5, ingredients:[["silver",30]] },
    { item:"frostner", level:4, stationLevel:6, ingredients:[["silver",60]] },
    { item:"draugr-fang", level:2, stationLevel:3, ingredients:[["ancient-bark",5],["silver",10],["deer-hide",2],["guck",2]] },
    { item:"draugr-fang", level:3, stationLevel:4, ingredients:[["ancient-bark",10],["silver",20],["deer-hide",4],["guck",4]] },
    { item:"draugr-fang", level:4, stationLevel:5, ingredients:[["ancient-bark",20],["silver",40],["deer-hide",8],["guck",8]] },
    { item:"silver-knife", level:2, stationLevel:4, ingredients:[["wood",1],["silver",5],["leather-scraps",1],["iron",1]] },
    { item:"silver-knife", level:3, stationLevel:5, ingredients:[["wood",2],["silver",10],["leather-scraps",2],["iron",2]] },
    { item:"silver-knife", level:4, stationLevel:6, ingredients:[["wood",4],["silver",20],["leather-scraps",4],["iron",4]] },
    { item:"flesh-rippers", level:2, stationLevel:4, ingredients:[["fenris-hair",1],["fenris-claw",1],["silver",1]] },
    { item:"flesh-rippers", level:3, stationLevel:5, ingredients:[["fenris-hair",2],["fenris-claw",2],["silver",2]] },
    { item:"flesh-rippers", level:4, stationLevel:6, ingredients:[["fenris-hair",4],["fenris-claw",4],["silver",4]] },
    { item:"silver-shield", level:2, stationLevel:4, ingredients:[["finewood",10],["silver",4]] },
    { item:"silver-shield", level:3, stationLevel:5, ingredients:[["finewood",20],["silver",8]] },
    { item:"scythe", level:2, stationLevel:3, ingredients:[["silver",5]] },
    { item:"scythe", level:3, stationLevel:4, ingredients:[["silver",10]] },

    { item:"drake-helmet", level:2, stationLevel:2, ingredients:[["silver",5]] },
    { item:"drake-helmet", level:3, stationLevel:3, ingredients:[["silver",10]] },
    { item:"drake-helmet", level:4, stationLevel:4, ingredients:[["silver",20]] },
    { item:"wolf-hide-chestpiece", level:2, stationLevel:3, ingredients:[["silver",5],["wolf-pelt",2]] },
    { item:"wolf-hide-chestpiece", level:3, stationLevel:4, ingredients:[["silver",10],["wolf-pelt",4]] },
    { item:"wolf-hide-chestpiece", level:4, stationLevel:5, ingredients:[["silver",20],["wolf-pelt",8]] },
    { item:"wolf-hide-trousers", level:2, stationLevel:3, ingredients:[["silver",5],["wolf-pelt",2],["wolf-fang",1]] },
    { item:"wolf-hide-trousers", level:3, stationLevel:4, ingredients:[["silver",10],["wolf-pelt",4],["wolf-fang",2]] },
    { item:"wolf-hide-trousers", level:4, stationLevel:5, ingredients:[["silver",20],["wolf-pelt",8],["wolf-fang",4]] },
    { item:"wolf-fur-cape", level:2, stationLevel:3, ingredients:[["wolf-pelt",4],["silver",2]] },
    { item:"wolf-fur-cape", level:3, stationLevel:4, ingredients:[["wolf-pelt",8],["silver",4]] },
    { item:"wolf-fur-cape", level:4, stationLevel:5, ingredients:[["wolf-pelt",16],["silver",8]] },
    { item:"fenris-hood", level:2, stationLevel:3, ingredients:[["fenris-hair",5],["wolf-pelt",4]] },
    { item:"fenris-hood", level:3, stationLevel:4, ingredients:[["fenris-hair",10],["wolf-pelt",8]] },
    { item:"fenris-hood", level:4, stationLevel:5, ingredients:[["fenris-hair",20],["wolf-pelt",16]] },
    ...["fenris-coat","fenris-leggings"].flatMap(item => [
      { item, level:2, stationLevel:3, ingredients:[["fenris-hair",5],["wolf-pelt",3],["leather-scraps",4]] as Array<[string,number]> },
      { item, level:3, stationLevel:4, ingredients:[["fenris-hair",10],["wolf-pelt",6],["leather-scraps",8]] as Array<[string,number]> },
      { item, level:4, stationLevel:5, ingredients:[["fenris-hair",20],["wolf-pelt",12],["leather-scraps",16]] as Array<[string,number]> }
    ])
  ],
  stats: [
    ["crystal-battleaxe","slash_damage","90"],["crystal-battleaxe","chop","50"],["crystal-battleaxe","spirit_damage","30"],["crystal-battleaxe","durability","200"],
    ["fang-spear","pierce_damage","75"],["fang-spear","durability","100"],
    ["silver-sword","slash_damage","75"],["silver-sword","spirit_damage","30"],["silver-sword","durability","200"],
    ["frostner","blunt_damage","35"],["frostner","frost_damage","40"],["frostner","spirit_damage","20"],["frostner","durability","200"],
    ["draugr-fang","pierce_damage","47"],["draugr-fang","poison_damage","5"],["draugr-fang","durability","100"],
    ["silver-knife","slash_damage","25"],["silver-knife","pierce_damage","25"],["silver-knife","spirit_damage","12"],["silver-knife","durability","200"],
    ["flesh-rippers","slash_damage","60"],["flesh-rippers","durability","300"],
    ["silver-shield","block_armor","60"],["silver-shield","durability","200"],
    ["drake-helmet","armor","20"],["wolf-hide-chestpiece","armor","20"],["wolf-hide-trousers","armor","20"],["wolf-fur-cape","armor","1"],
    ["fenris-hood","armor","10"],["fenris-coat","armor","10"],["fenris-leggings","armor","10"],
    ["wolf-sight","adrenaline","55"],["wolf-sight","duration","30","s"],
    ["crystal-heart","adrenaline","80"],["crystal-heart","duration","50","s"],
    ["wolf-jerky-x2","health","33"],["wolf-jerky-x2","stamina","33"],["wolf-jerky-x2","duration","30","min"],["wolf-jerky-x2","healing","3","hp/tick"],
    ["wolf-skewer","health","65"],["wolf-skewer","stamina","21"],["wolf-skewer","duration","25","min"],["wolf-skewer","healing","3","hp/tick"],
    ["eyescream","health","21"],["eyescream","stamina","65"],["eyescream","duration","25","min"],["eyescream","healing","1","hp/tick"],
    ["onion-soup","health","20"],["onion-soup","stamina","60"],["onion-soup","duration","20","min"],["onion-soup","healing","1","hp/tick"]
  ],
  resourceSources: [
    ["silver-ore","Mine hidden Silver Veins or Silver Deposits above roughly 120 m in the Mountains. Each break rolls 33% across 2–3 rolls for 1 ore; use the Wishbone to locate buried veins.","Добывайте скрытые серебряные жилы и залежи выше примерно 120 м в Горах. При разрушении идёт 2–3 броска с шансом 33% по 1 руде; для поиска под землёй используйте Дужку.",item("silver-ore")],
    ["silver","Smelt Silver Ore in a Smelter using Coal.","Переплавляйте Серебряную руду в Плавильне с углём.",item("silver")],
    ["obsidian","Mine black Obsidian deposits on high Mountain slopes with an Iron Pickaxe or better.","Добывайте чёрные залежи Обсидиана на высоких горных склонах Железной киркой или лучше.",item("obsidian")],
    ["crystal","Stone Golems always drop 8–12 Crystal.","Каменные големы гарантированно роняют 8–12 Кристаллов.",item("crystal")],
    ["crystal","Crystal formations also appear throughout Frost Caves and can be broken for additional Crystal.","Кристаллические образования также встречаются по всей Морозной пещере и дают дополнительный Кристалл при разрушении.",item("crystal")],
    ["freeze-gland","Drakes always drop 1–2 Freeze Glands.","Драконы гарантированно роняют 1–2 Морозные железы.",item("freeze-gland")],
    ["wolf-fang","Wolves have a 40% chance to drop 1 Wolf Fang; starred wolves multiply drop amounts.","Волки имеют 40% шанс уронить 1 Волчий клык; звёздные волки увеличивают количество добычи.",item("wolf-fang")],
    ["wolf-pelt","Wolves always drop 1–2 Wolf Pelts.","Волки гарантированно роняют 1–2 Волчьи шкуры.",item("wolf-pelt")],
    ["wolf-meat","Wolves always drop 1 Wolf Meat.","Волки гарантированно роняют 1 Волчье мясо.",item("wolf-meat")],
    ["onion-seeds","Abandoned Mountain log-cabin chests roll Onion Seeds at 14% per roll across 3–5 rolls, yielding 3–9 seeds.","Сундуки заброшенных горных хижин дают Семена лука с шансом 14% за бросок при 3–5 бросках, по 3–9 семян.",item("onion-seeds")],
    ["onion-seeds","Seed Onion plants give 3 Onion Seeds; Coral Cod can also yield 1–2 at 33%.","Семенные растения лука дают 3 Семени лука; Коралловая треска также может дать 1–2 семени с шансом 33%.",item("onion-seeds")],
    ["onion","Plant Onion Seeds with the Cultivator in suitable soil, then harvest mature Onions.","Посадите Семена лука культиватором в подходящей почве и соберите созревший Лук.",item("onion")],
    ["dragon-egg","Pick up Dragon Eggs from Drake nests on Mountain peaks. Three eggs are required to summon Moder; they weigh 200 each and cannot be teleported.","Подбирайте Драконьи яйца в гнёздах драконов на горных вершинах. Для призыва Моудер нужно три яйца; каждое весит 200 и не проходит через портал.",item("dragon-egg")],
    ["fenris-hair","Break hanging Fenris hides in Frost Caves for 1–2 Fenris Hair.","Разбивайте подвешенные шкуры Фенриса в Морозных пещерах — они дают 1–2 Шерсти Фенриса.",item("fenris-hair")],
    ["fenris-hair","Break hanging hair strands in Frost Caves for 1 Fenris Hair each.","Разбивайте свисающие пряди шерсти в Морозных пещерах — каждая даёт 1 Шерсть Фенриса.",item("fenris-hair")],
    ["fenris-claw","Loot Fenris Claws from shrine/loot areas inside Frost Caves; they are cave-specific crafting loot for Flesh Rippers and braziers.","Ищите Когти Фенриса в святилищах и лут-зонах Морозных пещер; это специальная пещерная добыча для Разрывателей плоти и жаровен.",item("fenris-claw")],
    ["silver-battle-idol","Frost Cave chests roll Silver Battle Idol at about 1% per roll across 3–5 rolls.","Сундуки Морозных пещер дают Серебряный боевой идол примерно с шансом 1% за бросок при 3–5 бросках.",item("silver-battle-idol")],
    ["silver-battle-idol","Abandoned Mountain log-cabin chests also roll it at about 1% per roll across 3–5 rolls; rarer Swamp chest routes exist too.","Сундуки заброшенных горных хижин также дают его примерно с шансом 1% за бросок при 3–5 бросках; есть и более редкие болотные источники.",item("silver-battle-idol")],
    ["silver-protection-idol","Frost Cave chests roll Silver Protection Idol at about 2% per roll across 3–5 rolls.","Сундуки Морозных пещер дают Серебряный защитный идол примерно с шансом 2% за бросок при 3–5 бросках.",item("silver-protection-idol")],
    ["silver-protection-idol","Abandoned Mountain log-cabin chests roll it at about 1% per roll across 3–5 rolls; rarer Swamp chest routes exist too.","Сундуки заброшенных горных хижин дают его примерно с шансом 1% за бросок при 3–5 бросках; есть и более редкие болотные источники.",item("silver-protection-idol")],
    ["scythe-handle","Buy from the Bog Witch for 200 coins after Moder is defeated.","Покупается у Болотной ведьмы за 200 монет после победы над Моудер.",item("scythe-handle")],
    ["drake-trophy","Drakes drop a trophy at 10%.","Драконы роняют трофей с шансом 10%.",item("drake-trophy")],
    ["wolf-trophy","Wolves drop a trophy at 10%.","Волки роняют трофей с шансом 10%.",item("wolf-trophy")],
    ["fenring-trophy","Fenrings roaming the Mountains at night drop a trophy at 10%.","Фенринги, появляющиеся в Горах ночью, роняют трофей с шансом 10%.",item("fenring-trophy")],
    ["stone-golem-trophy","Stone Golems drop a trophy at 5%.","Каменные големы роняют трофей с шансом 5%.",item("stone-golem-trophy")],
    ["cultist-trophy","Cultists inside Frost Caves drop a trophy at 10%.","Культисты в Морозных пещерах роняют трофей с шансом 10%.",item("cultist-trophy")]
  ]
};

export const ensureMountainCatalog = (env: Env): Promise<void> => applyCatalogSeed(env, mountainSeed);
